title: Jason Gianakopulos 
logo: /assets/img/logo.png
description: Developer and researcher specializing in web development, cybersecurity, information security and OSINT. Based in California.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
