title: Jason Gianakopulos - Developer & Security Enthusiast
logo: /assets/img/logo.png
description: Developer and researcher specializing in web development, cybersecurity, and OSINT. Based in California.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
